name: Ansible-Tasks
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  Setup:
    name: Run Ansible Playbook against new OCP4 cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ocp4-ansible-roles external repo
        uses: actions/checkout@v2
        with:
          repository: luiscachog/ocp4-ansible-roles
          path: ansible-tasks

      - name: Download Artifacts from Cluster Deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yaml
          name: ocp-artifact
          path: ocp-artifact

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f ansible-tasks/requirements.txt ]; then
            pip install -r ansible-tasks/requirements.txt
          fi

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
          oc: "${{secrets.OCP_CLIENT_VERSION}}"

      - name: Run ansible playbook
        run: |
          cp ocp-artifact/auth/kubeconfig $GITHUB_WORKSPACE/kubeconfig
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
          ansible-playbook ansible-tasks/main.yaml
