name: Sync
on:
  workflow_dispatch:
  
env:
  OCP_CLUSTER_NAME: rosa-5828n
  OCP_VERSION: 4.10.16

jobs:
  job1:
    uses: .github/workflows/rosa-test.yaml@v1

  create:
    strategy:
      matrix:
        include:
          - environment: rosa
            url: ${{ needs.job1.outputs.rosa_api_url }}
            user: ROSA_OCP_CLUSTER_USER
            password: ROSA_OCP_CLUSTER_PASSWORD
    env:
      OCP_CLUSTER_URL: ${{ matrix.url }}
      OCP_CLUSTER_USER: ${{ secrets[matrix.user] }}
      OCP_CLUSTER_PASSWORD: ${{ secrets[matrix.password] }}
      
    name: Test Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: ${{ env.OCP_VERSION }}
          
      - name: OCP Login
        run: |
          echo "URL= ${{ env.OCP_CLUSTER_URL }}"
          echo "USER= ${{ env.OCP_CLUSTER_USER }}"
          echo "PASS= ${{ env.OCP_CLUSTER_PASSWORD }}"
          
          oc login ${{ env.OCP_CLUSTER_URL }} -u ${{ env.OCP_CLUSTER_USER }} -p ${{ env.OCP_CLUSTER_PASSWORD }}
